[http.routers]
  [http.routers.hornetapi-https]
    rule = "Host(`hornet.example.com`)"
    service = "hornetapi-loadbalancer"
    entryPoints = ["websecure"]
    [http.routers.hornetapi-https.tls]
        certResolver = "letsencrypt"

  [http.routers.hornetapi-http]
    rule = "Host(`hornet.example.com`)"
    service = "hornetapi-loadbalancer"
    entryPoints = ["web"]
    middlewares = ["hornet-scheme"]

  [[http.services.hornetapi-loadbalancer.loadBalancer.servers]]
    url = "http://localhost:14265" # to verify

  [http.middlewares]
    [http.middlewares.hornet-scheme.redirectScheme]
      scheme = "https" 
      permanent = true
